name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - uses: cachix/install-nix-action@v26
      - name: Nix cache
        uses: nix-community/cache-nix-action@135667ec418502fa5a3598af6fb9eb733888ce6a
        with:
          # restore and save a cache using this key
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          # if there's no cache hit, restore a cache by this prefix
          restore-prefixes-first-match: nix-${{ runner.os }}-
          # collect garbage until the Nix store size (in bytes) is at most this number
          # before trying to save a new cache
          gc-max-store-size-linux: 2G
      - name: Ensure flake.lock was committed
        run: ls flake.lock
      - run: nix flake check -L
      - run: nix build -L
      - run: glistix deps download
        shell: nix develop --command bash -e {0}
      - run: glistix test --target nix
        shell: nix develop --command bash -e {0}
      - run: glistix format --check src test
        shell: nix develop --command bash -e {0}
